### ISSUE TITLE
Add more messages to the list of comments generator 

### ISSUE THREAD

**Issue by pavelkeyzik** [pavelkeyzik/pr-approve-generator#1]
## What

We have a [list of mesages](https://github.com/pavelkeyzik/pr-approve-generator/blob/master/src/core/messages.js) to generate comments for Pull Requests. We need more messages, so feel free to add anything that you would add as PR comment to approve it. 

## Where

The file is located here `src/core/messages.js`

## Note

Please, don't use "LGTM", as the basic idea of the app is not having this comment on every PR 😊

**Comment by SahilChandravanshi** [comment]
Please, assign this to me.
