### ISSUE TITLE
Add unit tests for randomizer file

### ISSUE THREAD

**Issue by pavelkeyzik** [pavelkeyzik/pr-approve-generator#2]
## Issue

We have `src/core/randomizer.js` file that contains logic to generate messages. We want to have some unit tests to make sure that all generated messages are unique. 

The logic here is when we have 5 messages, and generate a new message, we just remove this message from messages array. That way we won't get this message again. If we removed last item from messages array, we just replaces our empty array with messages and we can start again from 5 messages.

If you have any question, please, let us know. The code is not ideal, so we can discuss changes that you need to make it more testable.

## Acceptance criteria

- we have a unit test that makes sure that all generated messages are unique
- we have a unit test that checks if we generated last item from messages, then we should update our messages with array, so when we'll try to generate again, we'll do this from new array that contains all messages

**Comment by batunpc** [comment]
Hi @pavelkeyzik  I want to investigate this as part of hacktoberfest

**Comment by pavelkeyzik** [comment]
@batunpc Hey👋 Sure! Go ahead 😊

**Comment by batunpc** [comment]
Thank you @pavelkeyzik  I would like to set a coverage provider to explicitly identify the covered/uncovered lines. I see that `pr-approve-generator` uses vitest, I think it would be great to use `istanbul` as coverage provider. More information could be found [here](https://vitest.dev/guide/coverage.html)

**Comment by pavelkeyzik** [comment]
That's a great idea @batunpc! As we don't have anything right now, you can use whatever you want 😊
