### ISSUE TITLE
Add unit tests for messages file

### ISSUE THREAD

**Issue by pavelkeyzik** [pavelkeyzik/pr-approve-generator#7]
## What

We want to add unit tests to our list of the messages

## Why

To get rid of duplications, or to ignore unwanted messages like "LGTM"

## Eng details

**Task 1**: Add unit test to make sure all messages are unique.
- `Good job` and `GOOD JOB` should fail as messages are the same
- `Great job 👍 ` and `Great job 💯` should fail as we should ignore emojis (Note: we should also remove this duplication in messages.js file, as at the moment we have that issue)
- `Good job` and `Great job` should have success message, as messages are unique

**Task 2**: Add unit test to make sure we don't have LGTM message

**Comment by batunpc** [comment]
Hello @pavelkeyzik I will take a look! 💯

**Comment by pavelkeyzik** [comment]
Thanks @batunpc I'll assign this to you 😊
