### ISSUE TITLE
Add option of changing emojis

### ISSUE THREAD

**Issue by makoteq** [pavelkeyzik/pr-approve-generator#9]
It would be cool to add an interaction by changing emojis when user clickin on it.
Below is short visualization of the idea

https://user-images.githubusercontent.com/42750440/196295394-3eca3240-1267-4240-a8fd-383d70d2c13f.mp4

If accepted im happy to work on that 😸

**Comment by pavelkeyzik** [comment]
Cześć @makoteq 👋 That's actually a really good idea. You can work on that and I'd be happy to see a PR with that update ☺️ The only thing I have is that we need to make it more obvious. When I see emoji I'm not thinking about clicking on it to update. Maybe we could add another button to generate emoji as well and have separate list for emoji?🤔
